___
# Ciência dos Dados - Projeto 1

Felipe Aron Nudelman Tabacinik

___
## Níveis de escolaridade em diferentes faixas (classificados por renda) da população brasileira

____
## Introdução

Este estudo pretende analisar a escolaridade da população brasileira e sua relação com cada uma das classes sociais/econômicas.

___
## Filtros da base de dados

In [1]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

In [2]:
print('Esperamos trabalhar no diretório')
print(os.getcwd())

Esperamos trabalhar no diretório
C:\Users\Felipe Aron\Documents\Insper\2A - DP\CD

#### Puxando o dataframe

In [3]:
dados = pd.read_csv('PES2011.csv',sep=',')

dados_new = pd.read_csv('PES2015.csv',sep=',')

#### Selecionando as variavéis de interesse

In [4]:
interesse = dados.loc[:,['UF','V0601','V0602','V6002','V6003','V6030','V0605','V6007','V6070','V0611','V7122','V4745','V4743','V4742','V4801','V4803','V4802']]

interesse_new = dados_new.loc[:,['UF','V0601','V0602','V6002','V6003','V6030','V0605','V6007','V6070','V0611','V7122','V4745','V4743','V4742','V4801','V4803','V4802']]

#### Regiões

Criando a variável 'Reg' que agloba os valores de UF em 5 grupos (Norte, Nordeste, Sudeste, Sul e Centro-Oeste)

In [5]:
interesse['Reg'] = interesse.UF
interesse.Reg[(interesse.UF>10)&(interesse.UF<=18)]=1
interesse.Reg[(interesse.UF>20)&(interesse.UF<30)]=2
interesse.Reg[(interesse.UF>30)&(interesse.UF<36)]=3
interesse.Reg[(interesse.UF>37)&(interesse.UF<46)]=4
interesse.Reg[(interesse.UF>49)&(interesse.UF<54)]=5

interesse_new['Reg'] = interesse_new.UF
interesse_new.Reg[(interesse_new.UF>10)&(interesse_new.UF<=17)]=1
interesse_new.Reg[(interesse_new.UF>20)&(interesse_new.UF<30)]=2
interesse_new.Reg[(interesse_new.UF>30)&(interesse_new.UF<36)]=3
interesse_new.Reg[(interesse_new.UF>37)&(interesse_new.UF<46)]=4
interesse_new.Reg[(interesse_new.UF>49)&(interesse_new.UF<54)]=5

C:\Anaconda\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
C:\Anaconda\lib\site-packages\ipykernel\__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
C:\Anaconda\lib\site-packages\ipykernel\__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Anaconda\lib\site-packages\ipykernel\__main__.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Anaconda\lib\site-packages\ipykernel\__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Anaconda\lib\site-packages\ipykernel\__main__.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Anaconda\lib\site-packages\ipykernel\__main__.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Anaconda\lib\site-packages\ipykernel\__main__.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Anaconda\lib\site-packages\ipykernel\__main__.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Anaconda\lib\site-packages\ipykernel\__main__.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

#### Limpando o dataframe

In [6]:
'''
interesse = interesse.dropna(0,how='any')
'''
'''
interesse.UF = interesse.UF.astype('category')
interesse.UF.cat.categories = ('Rondônia', 'Acre', 'Amazonas', 'Roraima', 'Pará', 'Amapá', 'Tocantins', 'Maranhão', 'Piauí', 'Ceará', 'Rio Grande do Norte', 'Paraíba', 'Pernambuco', 'Alagoas','Sergipe','Bahia', 'Minas Gerais', 'Espirito Santo', 'Rio de Janeiro', 'São Paulo', 'Paraná','Santa Catarina','Rio Grande do Sul', 'Mato Grosso do Sul', 'Mato Grosso', 'Goiás', 'DF')
interesse.V0601 = interesse.V0601.astype('category')
interesse.V0601.cat.categories = ('Sim', 'Não')
interesse.V0602 = interesse.V0602.astype('category')
interesse.V0602.cat.categories = ('Sim', 'Não')

interesse_new = interesse_new.dropna(0,how='any')
interesse_new.UF = interesse_new.UF.astype('category')
interesse_new.UF.cat.categories = ('Rondônia', 'Acre', 'Amazonas', 'Roraima', 'Pará', 'Amapá', 'Tocantins', 'Maranhão', 'Piauí', 'Ceará', 'Rio Grande do Norte', 'Paraíba', 'Pernambuco', 'Alagoas','Sergipe','Bahia', 'Minas Gerais', 'Espirito Santo', 'Rio de Janeiro', 'São Paulo', 'Paraná','Santa Catarina','Rio Grande do Sul', 'Mato Grosso do Sul', 'Mato Grosso', 'Goiás', 'DF')
interesse_new.V0601 = interesse_new.V0601.astype('category')
interesse_new.V0601.cat.categories = ('Sim', 'Não')
interesse_new.V0602 = interesse.V0602.astype('category')
interesse_new.V0602.cat.categories = ('Sim', 'Não')
'''

"\ninteresse.UF = interesse.UF.astype('category')\ninteresse.UF.cat.categories = ('Rondônia', 'Acre', 'Amazonas', 'Roraima', 'Pará', 'Amapá', 'Tocantins', 'Maranhão', 'Piauí', 'Ceará', 'Rio Grande do Norte', 'Paraíba', 'Pernambuco', 'Alagoas','Sergipe','Bahia', 'Minas Gerais', 'Espirito Santo', 'Rio de Janeiro', 'São Paulo', 'Paraná','Santa Catarina','Rio Grande do Sul', 'Mato Grosso do Sul', 'Mato Grosso', 'Goiás', 'DF')\ninteresse.V0601 = interesse.V0601.astype('category')\ninteresse.V0601.cat.categories = ('Sim', 'Não')\ninteresse.V0602 = interesse.V0602.astype('category')\ninteresse.V0602.cat.categories = ('Sim', 'Não')\n\ninteresse_new = interesse_new.dropna(0,how='any')\ninteresse_new.UF = interesse_new.UF.astype('category')\ninteresse_new.UF.cat.categories = ('Rondônia', 'Acre', 'Amazonas', 'Roraima', 'Pará', 'Amapá', 'Tocantins', 'Maranhão', 'Piauí', 'Ceará', 'Rio Grande do Norte', 'Paraíba', 'Pernambuco', 'Alagoas','Sergipe','Bahia', 'Minas Gerais', 'Espirito Santo', 'Rio de Janeiro', 'São Paulo', 'Paraná','Santa Catarina','Rio Grande do Sul', 'Mato Grosso do Sul', 'Mato Grosso', 'Goiás', 'DF')\ninteresse_new.V0601 = interesse_new.V0601.astype('category')\ninteresse_new.V0601.cat.categories = ('Sim', 'Não')\ninteresse_new.V0602 = interesse.V0602.astype('category')\ninteresse_new.V0602.cat.categories = ('Sim', 'Não')\n"

In [7]:
interesse

,UF,V0601,V0602,V6002,V6003,V6030,V0605,V6007,V6070,V0611,V7122,V4745,V4743,V4742,V4801,V4803,V4802,Reg
0,11,1,4,NaN,NaN,NaN,NaN,1.0,NaN,3.0,NaN,2,99.0,1.000000e+12,NaN,6,NaN,1
1,11,1,2,4.0,5.0,NaN,4.0,NaN,NaN,NaN,NaN,6,99.0,1.000000e+12,25.0,15,11.0,1
2,11,1,2,2.0,2.0,NaN,1.0,NaN,NaN,NaN,NaN,3,99.0,1.000000e+12,22.0,9,10.0,1
3,11,1,2,2.0,1.0,3.0,4.0,NaN,NaN,NaN,NaN,2,99.0,1.000000e+12,15.0,3,7.0,1
4,11,1,4,NaN,NaN,NaN,NaN,5.0,NaN,3.0,NaN,4,5.0,1.461000e+03,NaN,11,NaN,1
5,11,1,4,NaN,NaN,NaN,NaN,5.0,NaN,1.0,NaN,5,5.0,1.461000e+03,NaN,12,NaN,1
6,11,1,2,2.0,2.0,NaN,3.0,NaN,NaN,NaN,NaN,4,5.0,1.461000e+03,22.0,11,10.0,1
7,11,1,2,2.0,1.0,3.0,6.0,NaN,NaN,NaN,NaN,2,5.0,1.461000e+03,17.0,5,8.0,1
8,11,1,4,NaN,NaN,NaN,NaN,5.0,NaN,1.0,NaN,5,99.0,1.000000e+12,NaN,12,NaN,1
9,11,1,2,2.0,1.0,3.0,5.0,NaN,NaN,NaN,NaN,2,99.0,1.000000e+12,16.0,4,7.0,1
10,11,1,4,NaN,NaN,NaN,NaN,5.0,NaN,1.0,NaN,5,4.0,1.000000e+03,NaN,12,NaN,1
11,11,1,4,NaN,NaN,NaN,NaN,2.0,NaN,3.0,NaN,2,4.0,1.000000e+03,NaN,6,NaN,1
12,11,1,2,2.0,2.0,NaN,3.0,NaN,NaN,NaN,NaN,4,4.0,1.000000e+03,22.0,11,10.0,1
13,11,1,2,2.0,1.0,3.0,6.0,NaN,NaN,NaN,NaN,2,4.0,1.000000e+03,17.0,5,8.0,1
14,11,3,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4.0,1.000000e+03,NaN,1,NaN,1
15,11,1,4,NaN,NaN,NaN,NaN,1.0,NaN,3.0,NaN,2,4.0,1.000000e+03,NaN,4,NaN,1
16,11,1,4,NaN,NaN,NaN,NaN,1.0,NaN,3.0,NaN,2,4.0,8.600000e+02,NaN,4,NaN,1
17,11,1,4,NaN,NaN,NaN,NaN,1.0,NaN,3.0,NaN,2,4.0,8.600000e+02,NaN,6,NaN,1
18,11,1,4,NaN,NaN,NaN,NaN,4.0,1.0,3.0,NaN,2,4.0,8.600000e+02,NaN,8,NaN,1
19,11,1,2,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,4,4.0,8.600000e+02,22.0,10,10.0,1
20,11,1,4,NaN,NaN,NaN,NaN,4.0,1.0,1.0,NaN,3,4.0,8.600000e+02,NaN,9,NaN,1
21,11,1,4,NaN,NaN,NaN,NaN,8.0,NaN,3.0,NaN,6,6.0,2.500000e+03,NaN,14,NaN,1
22,11,1,4,NaN,NaN,NaN,NaN,2.0,NaN,3.0,NaN,2,4.0,5.500000e+02,NaN,8,NaN,1
23,11,1,4,NaN,NaN,NaN,NaN,2.0,NaN,3.0,NaN,2,4.0,5.500000e+02,NaN,9,NaN,1
24,11,1,4,NaN,NaN,NaN,NaN,8.0,NaN,1.0,NaN,7,4.0,5.500000e+02,NaN,15,NaN,1
25,11,1,4,NaN,NaN,NaN,NaN,5.0,NaN,1.0,NaN,5,4.0,5.500000e+02,NaN,12,NaN,1
26,11,1,4,NaN,NaN,NaN,NaN,1.0,NaN,3.0,NaN,2,4.0,1.015000e+03,NaN,3,NaN,1
27,11,1,4,NaN,NaN,NaN,NaN,1.0,NaN,3.0,NaN,2,4.0,1.015000e+03,NaN,5,NaN,1
28,11,1,4,NaN,NaN,NaN,NaN,5.0,NaN,1.0,NaN,5,4.0,1.015000e+03,NaN,12,NaN,1
29,11,1,4,NaN,NaN,NaN,NaN,8.0,NaN,1.0,NaN,7,4.0,1.050000e+03,NaN,16,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358889,53,1,2,4.0,1.0,1.0,7.0,NaN,NaN,NaN,NaN,2,7.0,4.850000e+03,10.0,7,5.0,5
358890,53,1,2,4.0,1.0,1.0,5.0,NaN,NaN,NaN,NaN,2,7.0,4.850000e+03,8.0,5,5.0,5
358891,53,1,2,2.0,1.0,3.0,2.0,NaN,NaN,NaN,NaN,1,7.0,4.850000e+03,13.0,1,7.0,5
358892,53,1,4,NaN,NaN,NaN,NaN,8.0,NaN,1.0,NaN,7,5.0,1.333000e+03,NaN,16,NaN,5
358893,53,1,2,4.0,5.0,NaN,4.0,NaN,NaN,NaN,NaN,6,5.0,1.333000e+03,25.0,15,11.0,5
358894,53,3,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,5.0,1.333000e+03,NaN,1,NaN,5
358895,53,1,4,NaN,NaN,NaN,NaN,8.0,NaN,1.0,NaN,7,7.0,3.500000e+03,NaN,16,NaN,5
358896,53,1,4,NaN,NaN,NaN,NaN,8.0,NaN,1.0,NaN,7,7.0,3.500000e+03,NaN,16,NaN,5
358897,53,1,4,NaN,NaN,NaN,NaN,8.0,NaN,1.0,NaN,7,7.0,7.966000e+03,NaN,16,NaN,5
358898,53,1,4,NaN,NaN,NaN,NaN,9.0,NaN,1.0,NaN,7,7.0,7.966000e+03,NaN,16,NaN,5
358899,53,1,2,4.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,2,7.0,7.966000e+03,20.0,8,8.0,5
358900,53,1,4,NaN,NaN,NaN,NaN,8.0,NaN,1.0,NaN,7,7.0,9.000000e+03,NaN,16,NaN,5
358901,53,1,4,NaN,NaN,NaN,NaN,8.0,NaN,1.0,NaN,7,7.0,9.000000e+03,NaN,16,NaN,5
358902,53,3,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,7.0,9.000000e+03,NaN,1,NaN,5
358903,53,1,4,NaN,NaN,NaN,NaN,8.0,NaN,1.0,NaN,7,99.0,1.000000e+12,NaN,16,NaN,5
358904,53,1,4,NaN,NaN,NaN,NaN,8.0,NaN,1.0,NaN,7,99.0,1.000000e+12,NaN,16,NaN,5
358905,53,1,4,NaN,NaN,NaN,NaN,8.0,NaN,1.0,NaN,7,99.0,1.000000e+12,NaN,16,NaN,5
358906,53,1,2,4.0,5.0,NaN,6.0,NaN,NaN,NaN,NaN,6,99.0,1.000000e+12,25.0,16,11.0,5
358907,53,1,2,2.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,1,99.0,1.000000e+12,2.0,1,2.0,5
358908,53,1,4,NaN,NaN,NaN,NaN,8.0,NaN,1.0,NaN,7,7.0,8.000000e+03,NaN,16,NaN,5
358909,53,1,4,NaN,NaN,NaN,NaN,8.0,NaN,1.0,NaN,7,7.0,8.000000e+03,NaN,16,NaN,5
358910,53,3,2,4.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,1,7.0,8.000000e+03,NaN,1,NaN,5
358911,53,1,4,NaN,NaN,NaN,NaN,8.0,NaN,1.0,NaN,7,7.0,5.500000e+03,NaN,16,NaN,5
358912,53,1,4,NaN,NaN,NaN,NaN,8.0,NaN,1.0,NaN,7,7.0,5.500000e+03,NaN,16,NaN,5
358913,53,1,2,4.0,1.0,3.0,5.0,NaN,NaN,NaN,NaN,2,7.0,5.500000e+03,16.0,4,7.0,5
358914,53,1,2,4.0,1.0,3.0,4.0,NaN,NaN,NaN,NaN,2,7.0,5.500000e+03,15.0,3,7.0,5
358915,53,1,4,NaN,NaN,NaN,NaN,8.0,NaN,1.0,NaN,7,6.0,2.625000e+03,NaN,16,NaN,5
358916,53,1,4,NaN,NaN,NaN,NaN,8.0,NaN,1.0,NaN,7,6.0,2.625000e+03,NaN,16,NaN,5
358917,53,1,2,4.0,2.0,NaN,3.0,NaN,NaN,NaN,NaN,4,6.0,2.625000e+03,22.0,11,10.0,5
358918,53,1,2,4.0,1.0,3.0,2.0,NaN,NaN,NaN,NaN,1,6.0,2.625000e+03,13.0,1,7.0,5

___
## Análise e Resultados

___
## Conclusão

Descreva aqui suas conclusões!